window.PRODUCTS = [
  {
    id: "alx-1",
    name: "6pcs Carbide CNC Router Bit Set",
    source: "AliExpress",
    price: 19.9,
    oldPrice: 29.9,
    rating: 4.8,
    sales: "2.3k+ sold",
    trend: 98,
    image: "https://images.unsplash.com/photo-1565084888279-aca607ecce0c?auto=format&fit=crop&w=900&q=80",
    link: "https://www.aliexpress.com/wholesale?SearchText=carbide+cnc+router+bit+set",
    description: "Precision bit pack for wood, acrylic, and light aluminum cuts."
  },
  {
    id: "tem-1",
    name: "3018 CNC Engraving Machine Kit",
    source: "Temu",
    price: 229,
    oldPrice: 279,
    rating: 4.7,
    sales: "900+ sold",
    trend: 97,
    image: "https://images.unsplash.com/photo-1581093448798-5f3509be221d?auto=format&fit=crop&w=900&q=80",
    link: "https://www.temu.com/search_result.html?search_key=3018%20cnc%20engraving%20machine",
    description: "Entry-level desktop CNC for fast prototyping and custom engraving."
  },
  {
    id: "alx-2",
    name: "V-Bit Chamfer Milling Cutter Set",
    source: "AliExpress",
    price: 17.5,
    oldPrice: 24.5,
    rating: 4.9,
    sales: "1.7k+ sold",
    trend: 95,
    image: "https://images.unsplash.com/photo-1581092588421-896dd51f7b68?auto=format&fit=crop&w=900&q=80",
    link: "https://www.aliexpress.com/wholesale?SearchText=v+bit+cnc+chamfer+set",
    description: "Clean bevels and lettering edges for polished finishing."
  },
  {
    id: "tem-2",
    name: "CNC Dust Shoe Vacuum Attachment",
    source: "Temu",
    price: 28.8,
    oldPrice: 39.9,
    rating: 4.6,
    sales: "1.2k+ sold",
    trend: 93,
    image: "https://images.unsplash.com/photo-1499578124509-1611b77778c8?auto=format&fit=crop&w=900&q=80",
    link: "https://www.temu.com/search_result.html?search_key=cnc%20dust%20shoe",
    description: "Keep your work surface cleaner and improve visibility while cutting."
  },
  {
    id: "alx-3",
    name: "ER11 Collet Chuck Extension Rod",
    source: "AliExpress",
    price: 15.2,
    oldPrice: 22.7,
    rating: 4.8,
    sales: "3k+ sold",
    trend: 94,
    image: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=900&q=80",
    link: "https://www.aliexpress.com/wholesale?SearchText=er11+collet+extension+rod",
    description: "Stable extension for deeper reach and better spindle flexibility."
  },
  {
    id: "tem-3",
    name: "Aluminum CNC Spoilboard Clamps (Set)",
    source: "Temu",
    price: 24.9,
    oldPrice: 34.9,
    rating: 4.7,
    sales: "870+ sold",
    trend: 92,
    image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=900&q=80",
    link: "https://www.temu.com/search_result.html?search_key=cnc%20spoilboard%20clamps",
    description: "Secure workholding accessories for reduced chatter and drift."
  },
  {
    id: "alx-4",
    name: "Offline Controller for 3018/3040 CNC",
    source: "AliExpress",
    price: 32.4,
    oldPrice: 46,
    rating: 4.8,
    sales: "1.1k+ sold",
    trend: 91,
    image: "https://images.unsplash.com/photo-1581092335878-5d9ff86ca2bf?auto=format&fit=crop&w=900&q=80",
    link: "https://www.aliexpress.com/wholesale?SearchText=3018+offline+controller",
    description: "Control your CNC jobs without needing a dedicated connected PC."
  },
  {
    id: "tem-4",
    name: "CNC Touch Probe Auto-Z Sensor",
    source: "Temu",
    price: 18.6,
    oldPrice: 26.5,
    rating: 4.6,
    sales: "640+ sold",
    trend: 90,
    image: "https://images.unsplash.com/photo-1594729095022-e2f6d2eece9c?auto=format&fit=crop&w=900&q=80",
    link: "https://www.temu.com/search_result.html?search_key=cnc%20touch%20probe",
    description: "Quickly zero tools for repeatable and reliable engraving depth."
  },
  {
    id: "alx-5",
    name: "CNC Stepper Motor Driver Board",
    source: "AliExpress",
    price: 42.7,
    oldPrice: 59.9,
    rating: 4.7,
    sales: "2k+ sold",
    trend: 89,
    image: "https://images.unsplash.com/photo-1555255707-c07966088b7b?auto=format&fit=crop&w=900&q=80",
    link: "https://www.aliexpress.com/wholesale?SearchText=cnc+stepper+driver+board",
    description: "Reliable controller board upgrade for smoother motion control."
  },
  {
    id: "tem-5",
    name: "Mini Mist Coolant Spray System",
    source: "Temu",
    price: 35.5,
    oldPrice: 49.8,
    rating: 4.7,
    sales: "540+ sold",
    trend: 88,
    image: "https://images.unsplash.com/photo-1581094288338-2314dddb7ece?auto=format&fit=crop&w=900&q=80",
    link: "https://www.temu.com/search_result.html?search_key=cnc%20mist%20coolant%20spray",
    description: "Improves tool life and finish quality on longer machining runs."
  }
];
